# Generated by Django 4.2.1 on 2023-10-23 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('esp_tecnica', models.TextField()),
                ('imagen', models.ImageField(upload_to='productos/imagenes')),
                ('archivo', models.FileField(upload_to='productos/documentos')),
                ('marca', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='main.marca')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tipo')),
            ],
        ),
    ]
